spherical_angle_bins: 10
egosphere_nodes: 20000
uncertainty_lower_bound: -100
neighbour_angle_threshold: 3.0 # degrees
mahalanobis_distance_threshold: 1000000000000.0
mean: [0.0, 0.0, 0.0]
standard_deviation: [1.0, 1.0, 1.0]
field_of_view: 89

