egosphere_nodes: 20000
uncertainty_lower_bound: -100
neighbour_angle_threshold: 0.8 # degrees
mahalanobis_distance_threshold: 100000000000000.0
mean: [0.0, 0.0, 0.0]
standard_deviation: [0.5,0.5,0.5]
prior_mean_distance: 1000
pior_std_dev_distance: 0.000001
field_of_view: 134
sensory_filtering_sphere_radius: 0.5
update_frequency: 25
pan_abs_limit: 0.9
tilt_abs_limit: 0.3
update_mode: true
logpolar: false
resample: false
ucb: true


