rings: 256
min_radius: 1
interp: 1
full: 0
sectors: 256
sp: 0
min_disparity: -30
disparities: 80
sigma: 3.0
occ_likelihood: 0.1
pole: 0.6
spherical_theta_bins: 100
spherical_phi_bins: 100
shell_radius: 1.0
high_pass: true
